dist: trusty
language: node_js
notifications:
  email: false
node_js: lts/*
stages:
  - test
  - name: deploy
    if: branch = master and type != pull_request
jobs:
  include:
    - stage: test
      script:
        - npm run format:check
        - npm run lint
        - npm run test
        - npm run build:all
      # deploy:
      #   provider: script
      #   skip_cleanup: true
      #   script:
      #     - npm run release
