dist: trusty
language: node_js
notifications:
  email: false
node_js: lts/*
stages:
  - test
jobs:
  include:
    - stage: test
      script:
        - npm run format:check
        - npm run lint
        - npm run test
        - npm run build:all
      # deploy:
      #   provider: script
      #   skip_cleanup: true
      #   script:
      #     - npm run release
      #   on:
      #     tags: false
      #     all_branches: true
      #     condition: '$TRAVIS_BRANCH =~ ^(master)$'
